### ISSUE TITLE
账号密码输入123登录不了

### ISSUE THREAD

**Issue by victor-fa** [zjinh/CloudDisk#19]
账号密码输入123登录不了
![image](https://user-images.githubusercontent.com/17930138/88050177-ef5c0f00-cb88-11ea-92b8-0d0e1d8ec9ba.png)

**Comment by 0x233-lh** [comment]
同问，输入账号密码无反应，也无法进行注册

**Comment by zjinh** [comment]
后台服务下线了，整个后台正在重构


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zjinh/CloudDisk"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月24日(星期五) 下午2:58
收件人:&nbsp;"zjinh/CloudDisk"<CloudDisk@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [zjinh/CloudDisk] 账号密码输入123登录不了 (#19)





 
同问，输入账号密码无反应，也无法进行注册

**Comment by zjinh** [comment]
后端在重构------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;0x233&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年7月24日(星期五) 下午2:58
收件人:&nbsp;&quot;zjinh/CloudDisk&quot;<CloudDisk@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [zjinh/CloudDisk] 账号密码输入123登录不了 (#19)

**Comment by 0x233-lh** [comment]
> 后台服务下线了，整个后台正在重构
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "zjinh/CloudDisk" <notifications@github.com&gt;; 发送时间:&nbsp;2020年7月24日(星期五) 下午2:58 收件人:&nbsp;"zjinh/CloudDisk"<CloudDisk@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;Re: [zjinh/CloudDisk] 账号密码输入123登录不了 (#19) 同问，输入账号密码无反应，也无法进行注册 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

哎呀，看来有点不凑巧，想体验一下的~

**Comment by zjinh** [comment]
请手动修改请求接口地址 为 http://api.zjinh.cn



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "0x233"<notifications@github.com&gt;; 
发送时间: 2020年7月24日(星期五) 下午2:58
收件人: "zjinh/CloudDisk"<CloudDisk@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: Re: [zjinh/CloudDisk] 账号密码输入123登录不了 (#19)





 
同问，输入账号密码无反应，也无法进行注册
 
&mdash;

**Comment by zjinh** [comment]
修改接口地址 为 http://zjinh.cn



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "0x233"<notifications@github.com&gt;; 
发送时间: 2020年7月24日(星期五) 下午3:43
收件人: "zjinh/CloudDisk"<CloudDisk@noreply.github.com&gt;; 
抄送: "ZJINH"<2665229856@QQ.COM&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [zjinh/CloudDisk] 账号密码输入123登录不了 (#19)





  
后台服务下线了，整个后台正在重构
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "zjinh/CloudDisk" <notifications@github.com&gt;; 发送时间:&nbsp;2020年7月24日(星期五) 下午2:58 收件人:&nbsp;"zjinh/CloudDisk"<CloudDisk@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;Re: [zjinh/CloudDisk] 账号密码输入123登录不了 (#19) 同问，输入账号密码无反应，也无法进行注册 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
哎呀，看来有点不凑巧，想体验一下的~

**Comment by zjinh** [comment]
你们想要体验的 重新克隆代码吧





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zjinh/CloudDisk"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月24日(星期五) 下午2:58
收件人:&nbsp;"zjinh/CloudDisk"<CloudDisk@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [zjinh/CloudDisk] 账号密码输入123登录不了 (#19)





 
同问，输入账号密码无反应，也无法进行注册

**Comment by zjinh** [comment]
修改接口地址 为 http://zjinh.cn

**Comment by zjinh** [comment]
请自行注册，注册完成即可登录，无需等待邮件

**Comment by victor-fa** [comment]
注册失败了

**Comment by zjinh** [comment]
再试一次




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "stormfa"<notifications@github.com&gt;; 
发送时间: 2020年7月24日(星期五) 下午4:47
收件人: "zjinh/CloudDisk"<CloudDisk@noreply.github.com&gt;; 
抄送: "ZJINH"<2665229856@QQ.COM&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [zjinh/CloudDisk] 账号密码输入123登录不了 (#19)





 
注册失败了

**Comment by victor-fa** [comment]
![image](https://user-images.githubusercontent.com/17930138/88375428-24a56e80-cdce-11ea-8495-2d7c45aad1a1.png)

[{"state":"error","msg":"\u6ce8\u518c\u5931\u8d25"}]

还是失败了

**Comment by zjinh** [comment]
应该可以了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "stormfa"<notifications@github.com&gt;; 
发送时间: 2020年7月24日(星期五) 下午4:53
收件人: "zjinh/CloudDisk"<CloudDisk@noreply.github.com&gt;; 
抄送: "ZJINH"<2665229856@QQ.COM&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [zjinh/CloudDisk] 账号密码输入123登录不了 (#19)





 

 
[{"state":"error","msg":"\u6ce8\u518c\u5931\u8d25"}]
 
还是失败了
 
&mdash;

**Comment by victor-fa** [comment]
可以了 nice

**Comment by zjinh** [comment]
嗯 感觉不错的话 点个star吧



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "stormfa"<notifications@github.com&gt;; 
发送时间: 2020年7月24日(星期五) 下午5:06
收件人: "zjinh/CloudDisk"<CloudDisk@noreply.github.com&gt;; 
抄送: "ZJINH"<2665229856@QQ.COM&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [zjinh/CloudDisk] 账号密码输入123登录不了 (#19)





 
可以了 nice
 
&mdash;

**Comment by victor-fa** [comment]
当然，早start了^_^
