### ISSUE TITLE
修改接口为http://zjinh.cn后，上传接口失败了

### ISSUE THREAD

**Issue by victor-fa** [zjinh/CloudDisk#20]
![image](https://user-images.githubusercontent.com/17930138/88871156-bfc49b00-d249-11ea-9d38-e266d6a08a82.png)

![image](https://user-images.githubusercontent.com/17930138/88871103-9c99eb80-d249-11ea-810c-c847b5e64849.png)

如图所示，上传报错了

**Comment by zjinh** [comment]
应该可以了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zjinh/CloudDisk"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月30日(星期四) 上午9:48
收件人:&nbsp;"zjinh/CloudDisk"<CloudDisk@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[zjinh/CloudDisk] 修改接口为http://zjinh.cn后，上传接口失败了 (#20)





 

 

 
如图所示，上传报错了

**Comment by victor-fa** [comment]
虽然上传成功了，但是上传后刷新报错
![image](https://user-images.githubusercontent.com/17930138/88886570-55bded00-d26d-11ea-8cb3-9ce32c9abd6e.png)

且双击打开图片，加载失败了

**Comment by zjinh** [comment]
可以了。






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "stormfa"<notifications@github.com&gt;; 
发送时间: 2020年7月30日(星期四) 下午2:04
收件人: "zjinh/CloudDisk"<CloudDisk@noreply.github.com&gt;; 
抄送: "ZJINH"<2665229856@QQ.COM&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [zjinh/CloudDisk] 修改接口为http://zjinh.cn后，上传接口失败了 (#20)





 
虽然上传成功了，但是上传后刷新报错
 
 
且双击打开图片，加载失败了

**Comment by victor-fa** [comment]
上传接口报错：
![image](https://user-images.githubusercontent.com/17930138/88887152-70449600-d26e-11ea-8b6f-ebd8c6665d5c.png)
![image](https://user-images.githubusercontent.com/17930138/88887166-78043a80-d26e-11ea-9d15-42248d4364a2.png)

**Comment by zjinh** [comment]
，，，，，，自己重试



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "stormfa"<notifications@github.com&gt;; 
发送时间: 2020年7月30日(星期四) 下午2:11
收件人: "zjinh/CloudDisk"<CloudDisk@noreply.github.com&gt;; 
抄送: "ZJINH"<2665229856@QQ.COM&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [zjinh/CloudDisk] 修改接口为http://zjinh.cn后，上传接口失败了 (#20)





 
上传接口报错：
 
 
 
&mdash;

**Comment by victor-fa** [comment]
成功了o(￣▽￣)ｄ
