### ISSUE TITLE
网站好像挂了

### ISSUE THREAD

**Issue by xlzy520** [zjinh/CloudDisk#37]

**Comment by zjinh** [comment]
什么网站




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zjinh/CloudDisk"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月8日(星期二) 凌晨0:23
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[zjinh/CloudDisk] 网站好像挂了 (#37)

**Comment by xlzy520** [comment]
网盘的官网


 
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年6月8日 10:14:18
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zjinh/CloudDisk] 网站好像挂了 (#37)




 什么网站 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "zjinh/CloudDisk"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2021年6月8日(星期二) 凌晨0:23 
 ***@***.***&amp;gt;; 
 ***@***.***&amp;gt;; 
 主题:&amp;nbsp;[zjinh/CloudDisk] 网站好像挂了 (#37)

**Comment by zjinh** [comment]
我这里看着是正常的，给个具体网址。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月8日(星期二) 上午10:28
收件人: ***@***.***&gt;; 
抄送: "ZJINH"<2665229856@QQ.COM&gt;; ***@***.***&gt;; 
主题: Re: [zjinh/CloudDisk] 网站好像挂了 (#37)





 网盘的官网 
 
 
   
 ---原始邮件--- 
 发件人: ***@***.***&amp;gt; 
 发送时间: 2021年6月8日 10:14:18 
 收件人: ***@***.***&amp;gt;; 
 抄送: ***@***.******@***.***&amp;gt;; 
 主题: Re: [zjinh/CloudDisk] 网站好像挂了 (#37) 
 
 
 
 
  什么网站  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:                                                                                                                        "zjinh/CloudDisk"                                                                                    ***@***.***&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2021年6月8日(星期二) 凌晨0:23  
  ***@***.***&amp;amp;gt;;  
  ***@***.***&amp;amp;gt;;  
  主题:&amp;amp;nbsp;[zjinh/CloudDisk] 网站好像挂了 (#37)

**Comment by xlzy520** [comment]
https://works.zjinh.cn/CloudDisk/




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zjinh/CloudDisk"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月8日(星期二) 上午10:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zjinh/CloudDisk] 网站好像挂了 (#37)





 我这里看着是正常的，给个具体网址。 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: ***@***.***&amp;gt;;  
 发送时间: 2021年6月8日(星期二) 上午10:28 
 收件人: ***@***.***&amp;gt;;  
 抄送: "ZJINH"<2665229856@QQ.COM&amp;gt;; ***@***.***&amp;gt;;  
 主题: Re: [zjinh/CloudDisk] 网站好像挂了 (#37) 
 
 
 
 
 
  网盘的官网  
   
   
     
  ---原始邮件---  
  发件人: ***@***.***&amp;amp;gt;  
  发送时间: 2021年6月8日 10:14:18  
  收件人: ***@***.***&amp;amp;gt;;  
  抄送: ***@***.******@***.***&amp;amp;gt;;  
  主题: Re: [zjinh/CloudDisk] 网站好像挂了 (#37)  
   
   
   
   
   什么网站   
     
     
     
     
   ------------------&amp;amp;amp;nbsp;原始邮件&amp;amp;amp;nbsp;------------------   
   发件人:                                                                                                                        "zjinh/CloudDisk"                                                                                    ***@***.***&amp;amp;amp;gt;;   
   发送时间:&amp;amp;amp;nbsp;2021年6月8日(星期二) 凌晨0:23   
   ***@***.***&amp;amp;amp;gt;;   
   ***@***.***&amp;amp;amp;gt;;   
   主题:&amp;amp;amp;nbsp;[zjinh/CloudDisk] 网站好像挂了 (#37)

**Comment by zjinh** [comment]
直接这样进入 https://works.zjinh.cn


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zjinh/CloudDisk"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月8日(星期二) 中午11:01
***@***.***&gt;;
抄送:&nbsp;"ZJINH"<2665229856@***@***.***&gt;;
主题:&nbsp;Re: [zjinh/CloudDisk] 网站好像挂了 (#37)





 https://works.zjinh.cn/CloudDisk/ 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "zjinh/CloudDisk"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2021年6月8日(星期二) 上午10:30 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [zjinh/CloudDisk] 网站好像挂了 (#37) 
 
 
 
 
 
  我这里看着是正常的，给个具体网址。  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人: ***@***.***&amp;amp;gt;;   
  发送时间: 2021年6月8日(星期二) 上午10:28  
  收件人: ***@***.***&amp;amp;gt;;   
  抄送: "ZJINH"<2665229856@QQ.COM&amp;amp;gt;; ***@***.***&amp;amp;gt;;   
  主题: Re: [zjinh/CloudDisk] 网站好像挂了 (#37)  
   
   
   
   
   
   网盘的官网   
     
     
       
   ---原始邮件---   
   发件人: ***@***.***&amp;amp;amp;gt;   
   发送时间: 2021年6月8日 10:14:18   
   收件人: ***@***.***&amp;amp;amp;gt;;   
   抄送: ***@***.******@***.***&amp;amp;amp;gt;;   
   主题: Re: [zjinh/CloudDisk] 网站好像挂了 (#37)   
     
     
     
     
    什么网站    
       
       
       
       
    ------------------&amp;amp;amp;amp;nbsp;原始邮件&amp;amp;amp;amp;nbsp;------------------    
    发件人:                                                                                                                        "zjinh/CloudDisk"                                                                                    ***@***.***&amp;amp;amp;amp;gt;;    
    发送时间:&amp;amp;amp;amp;nbsp;2021年6月8日(星期二) 凌晨0:23    
    ***@***.***&amp;amp;amp;amp;gt;;    
    ***@***.***&amp;amp;amp;amp;gt;;    
    主题:&amp;amp;amp;amp;nbsp;[zjinh/CloudDisk] 网站好像挂了 (#37)

**Comment by xlzy520** [comment]
那你About那里的地址需要改一下
